/* Public Round 2 shortlist for IEEE MASATHON 2026.
 * Contact numbers from the organizer sheet are intentionally excluded.
 */
export const MASATHON_SHORTLIST = [
    { id: 1, team: 'Vishak Senthilkumar & Team', college: 'Anna University', domain: 'Game' },
    { id: 2, team: 'Jasim & Team', college: 'Anna University', domain: 'Game' },
    { id: 3, team: 'Rajeswari P. & Team', college: 'Anna University', domain: 'AI' },
    { id: 4, team: 'Karthikeyan Manikandan & Team', college: 'Anna University', domain: 'Game' },
    { id: 5, team: 'Mythili P. & Team', college: 'Anna University', domain: 'Game' },
    { id: 6, team: 'Kiruthika S. R. & Team', college: 'Chennai Institute of Technology', domain: 'Game' },
    { id: 7, team: 'Abdul Whajidh S. & Team', college: 'Chennai Institute of Technology', domain: 'AI' },
    { id: 8, team: 'Rahina Yasmin R. & Team', college: 'IFET College of Engineering', domain: 'AI' },
    { id: 9, team: 'Andrew Ben & Team', college: 'IFET College of Engineering', domain: 'Game' },
    { id: 10, team: 'M. Arunya & Team', college: 'J.P. College of Engineering, Ayikudi, Tenkasi', domain: 'AI' },
    { id: 11, team: 'Yogesh R. & Team', college: 'K.S. Rangasamy College of Technology', domain: 'Game' },
    { id: 12, team: 'Sahaya Sharmila A. & Team', college: 'Kangeyam Institute of Technology', domain: 'AI' },
    { id: 13, team: 'Anish Fathima A. & Team', college: 'Kangeyam Institute of Technology', domain: 'Game' },
    { id: 14, team: 'Dhakshata S. & Team', college: 'Knowledge Institute of Technology', domain: 'AI' },
    { id: 15, team: 'Lathika A. & Team', college: 'Meenakshi Sundararajan Engineering College', domain: 'Game' },
    { id: 16, team: 'Devanand R. & Team', college: 'Nandha Engineering College', domain: 'AI' },
    { id: 17, team: 'Sabarish J. & Team', college: 'Panimalar Engineering College', domain: 'AI' },
    { id: 18, team: 'Nitish & Team', college: 'Panimalar Engineering College', domain: 'AI' },
    { id: 19, team: 'Divakar M. & Team', college: 'R.M.K. Engineering College', domain: 'AI' },
    { id: 20, team: 'Udaya Velan M. & Team', college: 'S.A. Engineering College', domain: 'Game' },
    { id: 21, team: 'Vinay Vighnesh S. & Team', college: 'Sri Eshwar College of Engineering', domain: 'AI' },
    { id: 22, team: 'Nikitha A. S. EIE & Team', college: 'Sri Ramakrishna Engineering College', domain: 'AI' },
    { id: 23, team: 'Priyadharshini V. & Team', college: 'Sri Sairam Engineering College', domain: 'Game' },
    { id: 24, team: 'Shanmughapriya B. & Team', college: 'Sri Sairam Engineering College', domain: 'AI' },
    { id: 25, team: 'Sankara Narayana S. V. & Team', college: 'Sri Sairam Institute of Technology', domain: 'Game' },
    { id: 26, team: 'Ganesh & Team', college: 'Sri Venkateshwaraa College of Technology', domain: 'AI' },
    { id: 27, team: 'Aashish Niranjan Barathykannan & Team', college: 'SRM Institute of Science and Technology', domain: 'AI' },
    { id: 28, team: 'Harini Narasimhan & Team', college: 'SSN College of Engineering', domain: 'Game' },
    { id: 29, team: 'Adithya Sivakumar & Team', college: 'SSN College of Engineering', domain: 'AI' },
    { id: 30, team: 'Sanjana Y. & Team', college: 'SSN College of Engineering', domain: 'Game' },
    { id: 31, team: 'Sadana A. S. & Team', college: "St. Joseph's Institute of Technology", domain: 'AI' },
    { id: 32, team: 'Nanthitha N. & Team', college: 'Thiagarajar College of Engineering', domain: 'AI' },
    { id: 33, team: 'Lathika M. & Team', college: 'Thiagarajar College of Engineering', domain: 'Game' },
    { id: 34, team: 'Gayathri M. & Team', college: 'Velalar College of Engineering and Technology', domain: 'Game' },
];
